import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import SessionWrapper from '@/components/SessionWrapper';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arthub",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    // <SessionWrapper>
    <html lang="en">
      <body className={inter.className}>

        {children}

      </body>
    </html>
    // </SessionWrapper>
  );
}
